USE hosenfabrik;

DROP TABLE IF EXISTS BESTELLUNG;

SHOW FIELDS FROM BESTELLUNG;

DROP TABLE IF EXISTS BESTELLUNG;
CREATE TABLE BESTELLUNG

(
    BestellungsID INTEGER,
    Bestelldatum DATE,

    PRIMARY KEY (BestellungsID)

);