USE hosenfabrik;

DROP TABLE IF EXISTS FERTIGUNGSAUFTRAG;

SHOW FIELDS FROM FERTIGUNGSAUFTRAG;

DROP TABLE IF EXISTS FERTIGUNGSAUFTRAG;
CREATE TABLE FERTIGUNGSAUFTRAG

(
    ProduktID INTEGER,
    FaNr INTEGER,
    Abgeschlossen BOOLEAN,

    PRIMARY KEY (ProduktID)


);