USE HOSENFABRIK;

DROP TABLE IF EXISTS GEWERBLICHER_KUNDE;

CREATE TABLE GEWERBLICHER_KUNDE

(
    KundenID CHAR(10) NOT NULL,
    Firmenname VARCHAR(255),
    PRIMARY KEY (KundenID)

);

ALTER TABLE GEWERBLICHER_KUNDE
    ADD CONSTRAINT FOREIGN KEY(KundenID) REFERENCES Kundenstamm(KundenID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

