USE hosenfabrik;

DROP TABLE IF EXISTS PRIVATER_KUNDE;

SHOW FIELDS FROM PRIVATER_KUNDE;

DROP TABLE IF EXISTS PRIVATER_KUNDE;
CREATE TABLE PRIVATER_KUNDE

(
    KundenID CHAR(10),
    Vorname VARCHAR(255),
    Nachname VARCHAR(255),
    PRIMARY KEY (KundenID)


);