USE hosenfabrik;

DROP TABLE IF EXISTS PRIVATER_KUNDE;

CREATE TABLE PRIVATER_KUNDE

(
    KundenID CHAR(10),
    Vorname VARCHAR(255),
    Nachname VARCHAR(255),
    PRIMARY KEY (KundenID)

);
ALTER TABLE PRIVATER_KUNDE
    ADD CONSTRAINT FOREIGN KEY(KundenID) REFERENCES Kundenstamm(KundenID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
